/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{clusterId}/agent-connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiAgentConnection"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/agent-connections/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/agent-connections/{agentConnectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    agentConnectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiAgentConnection"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    Priority?: components["schemas"]["JobMasterPriority"];
                    Status?: components["schemas"]["BucketStatus"];
                    AgentWorkerId?: string;
                    WorkerLane?: string;
                    BucketType?: components["schemas"]["BucketType"];
                    CountLimit?: number;
                    Offset?: number;
                    BucketIds?: string[];
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiBucketModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/buckets/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    Priority?: components["schemas"]["JobMasterPriority"];
                    Status?: components["schemas"]["BucketStatus"];
                    AgentWorkerId?: string;
                    WorkerLane?: string;
                    BucketType?: components["schemas"]["BucketType"];
                    CountLimit?: number;
                    Offset?: number;
                    BucketIds?: string[];
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/buckets/{bucketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    bucketId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiBucketModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiHostModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/hosts/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/hosts/{hostId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    hostId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiHostModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["JobMasterJobStatus"];
                    Statuses?: components["schemas"]["JobMasterJobStatus"][];
                    Priority?: components["schemas"]["JobMasterPriority"];
                    NextPlanExecutionAtTo?: string;
                    NextPlanExecutionAtFrom?: string;
                    ScheduledFrom?: string;
                    ScheduledTo?: string;
                    ProcessDeadlineTo?: string;
                    TriggerSourceTypes?: components["schemas"]["JobMasterTriggerSourceType"][];
                    SourceIds?: string[];
                    SourceId?: string;
                    JobDefinitionId?: string;
                    WorkerId?: string;
                    AgentConnectionId?: string;
                    HostId?: string;
                    BucketId?: string;
                    WorkerLane?: string;
                    CountLimit?: number;
                    Offset?: number;
                    MetadataFiltersJson?: string;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiJobModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["JobMasterJobStatus"];
                    Statuses?: components["schemas"]["JobMasterJobStatus"][];
                    Priority?: components["schemas"]["JobMasterPriority"];
                    NextPlanExecutionAtTo?: string;
                    NextPlanExecutionAtFrom?: string;
                    ScheduledFrom?: string;
                    ScheduledTo?: string;
                    ProcessDeadlineTo?: string;
                    TriggerSourceTypes?: components["schemas"]["JobMasterTriggerSourceType"][];
                    SourceIds?: string[];
                    SourceId?: string;
                    JobDefinitionId?: string;
                    WorkerId?: string;
                    AgentConnectionId?: string;
                    HostId?: string;
                    BucketId?: string;
                    WorkerLane?: string;
                    CountLimit?: number;
                    Offset?: number;
                    MetadataFiltersJson?: string;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiJobModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs/{id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiJobExecution"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Level?: components["schemas"]["ApiJobMasterLogLevel"];
                    Category?: components["schemas"]["ApiJobMasterLogCategory"];
                    ReferenceId?: string;
                    FromTimestamp?: string;
                    ToTimestamp?: string;
                    Keyword?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiLogItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiLogItem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/logs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Level?: components["schemas"]["ApiJobMasterLogLevel"];
                    Category?: components["schemas"]["ApiJobMasterLogCategory"];
                    ReferenceId?: string;
                    FromTimestamp?: string;
                    ToTimestamp?: string;
                    Keyword?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/recurring-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["RecurringScheduleStatus"];
                    StartAfterTo?: string;
                    StartAfterFrom?: string;
                    EndBeforeTo?: string;
                    EndBeforeFrom?: string;
                    CoverageUntil?: string;
                    IsJobCancellationPending?: boolean;
                    CanceledOrInactive?: boolean;
                    RecurringScheduleType?: components["schemas"]["RecurringScheduleType"];
                    JobDefinitionId?: string;
                    ProfileId?: string;
                    WorkerLane?: string;
                    MetadataFiltersJson?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiRecurringScheduleModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/recurring-schedules/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["RecurringScheduleStatus"];
                    StartAfterTo?: string;
                    StartAfterFrom?: string;
                    EndBeforeTo?: string;
                    EndBeforeFrom?: string;
                    CoverageUntil?: string;
                    IsJobCancellationPending?: boolean;
                    CanceledOrInactive?: boolean;
                    RecurringScheduleType?: components["schemas"]["RecurringScheduleType"];
                    JobDefinitionId?: string;
                    ProfileId?: string;
                    WorkerLane?: string;
                    MetadataFiltersJson?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/recurring-schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiRecurringScheduleModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    WorkerLane?: string;
                    Status?: components["schemas"]["AgentWorkerStatus"];
                    Mode?: components["schemas"]["AgentWorkerMode"];
                    IsAlive?: boolean;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiAgentWorker"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/workers/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    WorkerLane?: string;
                    Status?: components["schemas"]["AgentWorkerStatus"];
                    Mode?: components["schemas"]["AgentWorkerMode"];
                    IsAlive?: boolean;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/workers/{workerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    workerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiAgentWorker"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @enum {integer}
         */
        AgentWorkerMode: 1 | 2 | 3 | 4;
        /**
         * Format: int32
         * @enum {integer}
         */
        AgentWorkerStatus: 0 | 1 | 2;
        ApiAgentConnection: {
            id?: string | null;
            name?: string | null;
            repositoryTypeId?: string | null;
            fingerprint?: string | null;
            /** Format: date-time */
            lastHeartbeat?: string | null;
            /** Format: date-time */
            createdAt?: string;
            protectConnectionChanges?: boolean;
            isAlive?: boolean;
        };
        ApiAgentWorker: {
            clusterId?: string | null;
            id?: string | null;
            name?: string | null;
            agentConnectionId?: string | null;
            agentConnectionName?: string | null;
            /** Format: date-time */
            createdAt?: string;
            isAlive?: boolean;
            /** Format: date-time */
            stopRequestedAt?: string | null;
            /** Format: date-span */
            stopGracePeriod?: string | null;
            /** Format: date-time */
            lastHeartbeat?: string;
            mode?: components["schemas"]["AgentWorkerMode"];
            workerLane?: string | null;
            /** Format: double */
            parallelismFactor?: number;
            status?: components["schemas"]["AgentWorkerStatus"];
            hostId?: string | null;
            hostDisplayName?: string | null;
        };
        ApiBucketModel: {
            clusterId?: string | null;
            id?: string | null;
            name?: string | null;
            agentConnectionId?: string | null;
            agentConnectionName?: string | null;
            agentWorkerId?: string | null;
            hostId?: string | null;
            hostDisplayName?: string | null;
            repositoryTypeId?: string | null;
            priority?: components["schemas"]["JobMasterPriority"];
            status?: components["schemas"]["BucketStatus"];
            /** Format: date-time */
            createdAt?: string;
            color?: string | null;
            workerLane?: string | null;
            /** Format: date-time */
            lastStatusChangeAt?: string;
            bucketType?: components["schemas"]["BucketType"];
        };
        ApiHostModel: {
            id?: string | null;
            hostDisplayName?: string | null;
            processId?: string | null;
            /** Format: int32 */
            processorCount?: number | null;
            osDescription?: string | null;
            /** Format: date-time */
            lastHeartbeat?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            statisticsAt?: string | null;
            /** Format: double */
            cpuUsagePercent?: number | null;
            /** Format: int64 */
            memoryTotalBytes?: number | null;
            /** Format: int64 */
            memoryUsedBytes?: number | null;
            /** Format: int64 */
            diskAvailableBytes?: number | null;
            isAlive?: boolean;
        };
        ApiJobExecution: {
            id?: string | null;
            jobId?: string | null;
            /** Format: date-time */
            startedAt?: string;
            agentConnectionId?: string | null;
            agentConnectionName?: string | null;
            agentWorkerId?: string | null;
            bucketId?: string | null;
            hostId?: string | null;
            hostDisplayName?: string | null;
            /** Format: date-time */
            finalizedAt?: string | null;
            outcomeMessage?: string | null;
            outcome?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ApiJobMasterLogCategory: 1 | 2 | 3 | 4 | 5 | 6 | 7;
        /**
         * Format: int32
         * @enum {integer}
         */
        ApiJobMasterLogLevel: 0 | 1 | 2 | 3 | 4;
        ApiJobModel: {
            clusterId?: string | null;
            id?: string | null;
            jobDefinitionId?: string | null;
            triggerSourceType?: components["schemas"]["JobMasterTriggerSourceType"];
            bucketId?: string | null;
            agentConnectionId?: string | null;
            agentWorkerId?: string | null;
            hostId?: string | null;
            hostDisplayName?: string | null;
            priority?: components["schemas"]["JobMasterPriority"];
            /** Format: date-time */
            scheduledAt?: string;
            /** Format: date-time */
            nextPlanExecutionAt?: string | null;
            msgData?: {
                [key: string]: unknown;
            } | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            status?: components["schemas"]["JobMasterJobStatus"];
            /** Format: int32 */
            numberOfFailures?: number;
            /** Format: date-span */
            timeout?: string;
            /** Format: int32 */
            maxNumberOfRetries?: number;
            /** Format: date-time */
            createdAt?: string;
            sourceId?: string | null;
            /** Format: date-time */
            processDeadline?: string | null;
            /** Format: date-time */
            processStartedAt?: string | null;
            /** Format: date-time */
            finalizedAt?: string | null;
            workerLane?: string | null;
        };
        ApiLogItem: {
            id?: string | null;
            clusterId?: string | null;
            level?: components["schemas"]["ApiJobMasterLogLevel"];
            message?: string | null;
            category?: components["schemas"]["ApiJobMasterLogCategory"];
            referenceId?: string | null;
            /** Format: date-time */
            timestampUtc?: string;
            host?: string | null;
            sourceMember?: string | null;
            sourceFile?: string | null;
            /** Format: int32 */
            sourceLine?: number | null;
        };
        ApiRecurringScheduleModel: {
            clusterId?: string | null;
            id?: string | null;
            expression?: string | null;
            expressionTypeId?: string | null;
            jobDefinitionId?: string | null;
            staticDefinitionId?: string | null;
            profileId?: string | null;
            status?: components["schemas"]["RecurringScheduleStatus"];
            recurringScheduleType?: components["schemas"]["RecurringScheduleType"];
            /** Format: date-time */
            terminatedAt?: string | null;
            msgData?: {
                [key: string]: unknown;
            } | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            priority?: components["schemas"]["JobMasterPriority"];
            /** Format: int32 */
            maxNumberOfRetries?: number | null;
            /** Format: date-span */
            timeout?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startAfter?: string | null;
            /** Format: date-time */
            endBefore?: string | null;
            /** Format: date-time */
            lastPlanCoverageUntil?: string | null;
            /** Format: date-time */
            lastExecutedPlan?: string | null;
            hasFailedOnLastPlanExecution?: boolean | null;
            isJobCancellationPending?: boolean | null;
            /** Format: date-time */
            staticDefinitionLastEnsured?: string | null;
            workerLane?: string | null;
            isStaticIdle?: boolean;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        BucketStatus: 1 | 2 | 3 | 4 | 5 | 6;
        /**
         * Format: int32
         * @enum {integer}
         */
        BucketType: 1 | 2;
        /**
         * Format: int32
         * @enum {integer}
         */
        JobMasterJobStatus: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
        /**
         * Format: int32
         * @enum {integer}
         */
        JobMasterPriority: 1 | 2 | 3 | 4 | 5;
        /**
         * Format: int32
         * @enum {integer}
         */
        JobMasterTriggerSourceType: 1 | 2 | 3;
        /**
         * Format: int32
         * @enum {integer}
         */
        RecurringScheduleStatus: 1 | 2 | 3 | 4 | 5;
        /**
         * Format: int32
         * @enum {integer}
         */
        RecurringScheduleType: 2 | 3;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
