/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{clusterId}/agent-connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/agent-connections/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/agent-connections/{agentConnectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    agentConnectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    Priority?: components["schemas"]["JobMasterPriority"];
                    Status?: components["schemas"]["BucketStatus"];
                    AgentWorkerId?: string;
                    WorkerLane?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/buckets/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    Priority?: components["schemas"]["JobMasterPriority"];
                    Status?: components["schemas"]["BucketStatus"];
                    AgentWorkerId?: string;
                    WorkerLane?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/buckets/{bucketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    bucketId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/hosts/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/hosts/{hostId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    hostId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["JobMasterJobStatus"];
                    Statuses?: components["schemas"]["JobMasterJobStatus"][];
                    Priority?: components["schemas"]["JobMasterPriority"];
                    NextPlanExecutionAtTo?: string;
                    NextPlanExecutionAtFrom?: string;
                    ScheduledFrom?: string;
                    ScheduledTo?: string;
                    ProcessDeadlineTo?: string;
                    TriggerSourceTypes?: components["schemas"]["JobMasterTriggerSourceType"][];
                    SourceIds?: string[];
                    SourceId?: string;
                    JobDefinitionId?: string;
                    WorkerId?: string;
                    AgentConnectionId?: string;
                    HostId?: string;
                    BucketId?: string;
                    WorkerLane?: string;
                    CountLimit?: number;
                    Offset?: number;
                    MetadataFiltersJson?: string;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["JobMasterJobStatus"];
                    Statuses?: components["schemas"]["JobMasterJobStatus"][];
                    Priority?: components["schemas"]["JobMasterPriority"];
                    NextPlanExecutionAtTo?: string;
                    NextPlanExecutionAtFrom?: string;
                    ScheduledFrom?: string;
                    ScheduledTo?: string;
                    ProcessDeadlineTo?: string;
                    TriggerSourceTypes?: components["schemas"]["JobMasterTriggerSourceType"][];
                    SourceIds?: string[];
                    SourceId?: string;
                    JobDefinitionId?: string;
                    WorkerId?: string;
                    AgentConnectionId?: string;
                    HostId?: string;
                    BucketId?: string;
                    WorkerLane?: string;
                    CountLimit?: number;
                    Offset?: number;
                    MetadataFiltersJson?: string;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs/{id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Level?: components["schemas"]["ApiJobMasterLogLevel"];
                    SubjectType?: components["schemas"]["ApiJobMasterLogSubjectType"];
                    SubjectId?: string;
                    FromTimestamp?: string;
                    ToTimestamp?: string;
                    Keyword?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/logs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Level?: components["schemas"]["ApiJobMasterLogLevel"];
                    SubjectType?: components["schemas"]["ApiJobMasterLogSubjectType"];
                    SubjectId?: string;
                    FromTimestamp?: string;
                    ToTimestamp?: string;
                    Keyword?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/recurring-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["RecurringScheduleStatus"];
                    StartAfterTo?: string;
                    StartAfterFrom?: string;
                    EndBeforeTo?: string;
                    EndBeforeFrom?: string;
                    CoverageUntil?: string;
                    IsJobCancellationPending?: boolean;
                    CanceledOrInactive?: boolean;
                    RecurringScheduleType?: components["schemas"]["RecurringScheduleType"];
                    JobDefinitionId?: string;
                    ProfileId?: string;
                    WorkerLane?: string;
                    MetadataFiltersJson?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/recurring-schedules/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["RecurringScheduleStatus"];
                    StartAfterTo?: string;
                    StartAfterFrom?: string;
                    EndBeforeTo?: string;
                    EndBeforeFrom?: string;
                    CoverageUntil?: string;
                    IsJobCancellationPending?: boolean;
                    CanceledOrInactive?: boolean;
                    RecurringScheduleType?: components["schemas"]["RecurringScheduleType"];
                    JobDefinitionId?: string;
                    ProfileId?: string;
                    WorkerLane?: string;
                    MetadataFiltersJson?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/recurring-schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    WorkerLane?: string;
                    Status?: components["schemas"]["AgentWorkerStatus"];
                    Mode?: components["schemas"]["AgentWorkerMode"];
                    IsAlive?: boolean;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/workers/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    WorkerLane?: string;
                    Status?: components["schemas"]["AgentWorkerStatus"];
                    Mode?: components["schemas"]["AgentWorkerMode"];
                    IsAlive?: boolean;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/workers/{workerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    workerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @enum {integer}
         */
        AgentWorkerMode: 1 | 2 | 3 | 4;
        /**
         * Format: int32
         * @enum {integer}
         */
        AgentWorkerStatus: 0 | 1 | 2;
        /**
         * Format: int32
         * @enum {integer}
         */
        ApiJobMasterLogLevel: 0 | 1 | 2 | 3 | 4;
        /**
         * Format: int32
         * @enum {integer}
         */
        ApiJobMasterLogSubjectType: 1 | 2 | 3 | 4 | 5 | 6 | 7;
        /**
         * Format: int32
         * @enum {integer}
         */
        BucketStatus: 1 | 2 | 3 | 4 | 5 | 6;
        /**
         * Format: int32
         * @enum {integer}
         */
        JobMasterJobStatus: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
        /**
         * Format: int32
         * @enum {integer}
         */
        JobMasterPriority: 1 | 2 | 3 | 4 | 5;
        /**
         * Format: int32
         * @enum {integer}
         */
        JobMasterTriggerSourceType: 1 | 2 | 3;
        /**
         * Format: int32
         * @enum {integer}
         */
        RecurringScheduleStatus: 1 | 2 | 3 | 4 | 5;
        /**
         * Format: int32
         * @enum {integer}
         */
        RecurringScheduleType: 2 | 3;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
