/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{clusterId}/agent-connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/agent-connections/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/agent-connections/{agentConnectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    agentConnectionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    Priority?: components["schemas"]["JobMasterPriority"];
                    Status?: components["schemas"]["BucketStatus"];
                    AgentWorkerId?: string;
                    WorkerLane?: string;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiBucketModel"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/buckets/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    Priority?: components["schemas"]["JobMasterPriority"];
                    Status?: components["schemas"]["BucketStatus"];
                    AgentWorkerId?: string;
                    WorkerLane?: string;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/buckets/{bucketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    bucketId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiBucketModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{clusterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiClusterModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiHostModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/hosts/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/hosts/{hostId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    hostId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiHostModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["JobMasterJobStatus"];
                    Statuses?: components["schemas"]["JobMasterJobStatus"][];
                    Priority?: components["schemas"]["JobMasterPriority"];
                    ScheduledTo?: string;
                    ScheduledFrom?: string;
                    ProcessDeadlineTo?: string;
                    TriggerSourceTypes?: components["schemas"]["JobMasterTriggerSourceType"][];
                    SourceId?: string;
                    JobDefinitionId?: string;
                    WorkerId?: string;
                    AgentConnectionId?: string;
                    HostId?: string;
                    BucketId?: string;
                    WorkerLane?: string;
                    CountLimit?: number;
                    Offset?: number;
                    MetadataFiltersJson?: string;
                    OrderByProperty?: string;
                    OrderByAsc?: boolean;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiJobModel"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["JobMasterJobStatus"];
                    Statuses?: components["schemas"]["JobMasterJobStatus"][];
                    Priority?: components["schemas"]["JobMasterPriority"];
                    ScheduledTo?: string;
                    ScheduledFrom?: string;
                    ProcessDeadlineTo?: string;
                    TriggerSourceTypes?: components["schemas"]["JobMasterTriggerSourceType"][];
                    SourceId?: string;
                    JobDefinitionId?: string;
                    WorkerId?: string;
                    AgentConnectionId?: string;
                    HostId?: string;
                    BucketId?: string;
                    WorkerLane?: string;
                    CountLimit?: number;
                    Offset?: number;
                    MetadataFiltersJson?: string;
                    OrderByProperty?: string;
                    OrderByAsc?: boolean;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiJobModel"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Level?: components["schemas"]["ApiJobMasterLogLevel"];
                    SubjectType?: components["schemas"]["ApiJobMasterLogSubjectType"];
                    SubjectId?: string;
                    FromTimestamp?: string;
                    ToTimestamp?: string;
                    Keyword?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/logs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Level?: components["schemas"]["ApiJobMasterLogLevel"];
                    SubjectType?: components["schemas"]["ApiJobMasterLogSubjectType"];
                    SubjectId?: string;
                    FromTimestamp?: string;
                    ToTimestamp?: string;
                    Keyword?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/recurring-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["RecurringScheduleStatus"];
                    StartAfterTo?: string;
                    StartAfterFrom?: string;
                    EndBeforeTo?: string;
                    EndBeforeFrom?: string;
                    CoverageUntil?: string;
                    IsJobCancellationPending?: boolean;
                    CanceledOrInactive?: boolean;
                    RecurringScheduleType?: components["schemas"]["RecurringScheduleType"];
                    JobDefinitionId?: string;
                    ProfileId?: string;
                    WorkerLane?: string;
                    MetadataFiltersJson?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/recurring-schedules/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: components["schemas"]["RecurringScheduleStatus"];
                    StartAfterTo?: string;
                    StartAfterFrom?: string;
                    EndBeforeTo?: string;
                    EndBeforeFrom?: string;
                    CoverageUntil?: string;
                    IsJobCancellationPending?: boolean;
                    CanceledOrInactive?: boolean;
                    RecurringScheduleType?: components["schemas"]["RecurringScheduleType"];
                    JobDefinitionId?: string;
                    ProfileId?: string;
                    WorkerLane?: string;
                    MetadataFiltersJson?: string;
                    CountLimit?: number;
                    Offset?: number;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/recurring-schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    WorkerLane?: string;
                    Status?: components["schemas"]["AgentWorkerStatus"];
                    Mode?: components["schemas"]["AgentWorkerMode"];
                    IsAlive?: boolean;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/workers/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AgentConnectionId?: string;
                    WorkerLane?: string;
                    Status?: components["schemas"]["AgentWorkerStatus"];
                    Mode?: components["schemas"]["AgentWorkerMode"];
                    IsAlive?: boolean;
                };
                header?: never;
                path: {
                    clusterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{clusterId}/workers/{workerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clusterId: string;
                    workerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @enum {integer}
         */
        AgentWorkerMode: 1 | 2 | 3 | 4;
        /**
         * Format: int32
         * @enum {integer}
         */
        AgentWorkerStatus: 0 | 1 | 2;
        ApiBucketModel: {
            clusterId?: string | null;
            id?: string | null;
            name?: string | null;
            agentConnectionId?: string | null;
            agentConnectionName?: string | null;
            agentWorkerId?: string | null;
            hostId?: string | null;
            hostDisplayName?: string | null;
            repositoryTypeId?: string | null;
            priority?: components["schemas"]["JobMasterPriority"];
            status?: components["schemas"]["BucketStatus"];
            /** Format: date-time */
            createdAt?: string;
            color?: string | null;
            workerLane?: string | null;
            /** Format: date-time */
            lastStatusChangeAt?: string;
        };
        ApiClusterModel: {
            clusterId?: string | null;
            repositoryTypeId?: string | null;
            /** Format: date-span */
            defaultJobTimeout?: string;
            /** Format: date-span */
            transientThreshold?: string;
            /** Format: int32 */
            defaultMaxOfRetryCount?: number;
            clusterMode?: components["schemas"]["ClusterMode"];
            /** Format: int32 */
            maxMessageByteSize?: number;
            ianaTimeZoneId?: string | null;
            /** Format: date-span */
            dataRetentionTtl?: string | null;
            additionalConfig?: {
                [key: string]: unknown;
            } | null;
        };
        ApiHostModel: {
            id?: string | null;
            displayName?: string | null;
            /** Format: double */
            cpuUsagePercent?: number | null;
            /** Format: int64 */
            memoryTotalBytes?: number | null;
            /** Format: int64 */
            memoryUsedBytes?: number | null;
            /** Format: int32 */
            threadCount?: number;
            /** Format: int32 */
            handleCount?: number;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        ApiJobMasterLogLevel: 0 | 1 | 2 | 3 | 4;
        /**
         * Format: int32
         * @enum {integer}
         */
        ApiJobMasterLogSubjectType: 1 | 2 | 3 | 4 | 5 | 6 | 7;
        ApiJobModel: {
            clusterId?: string | null;
            id?: string | null;
            jobDefinitionId?: string | null;
            triggerSourceType?: components["schemas"]["JobMasterTriggerSourceType"];
            bucketId?: string | null;
            agentConnectionId?: string | null;
            agentWorkerId?: string | null;
            hostId?: string | null;
            hostDisplayName?: string | null;
            priority?: components["schemas"]["JobMasterPriority"];
            /** Format: date-time */
            originalScheduledAt?: string;
            /** Format: date-time */
            scheduledAt?: string;
            msgData?: {
                [key: string]: unknown;
            } | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            status?: components["schemas"]["JobMasterJobStatus"];
            /** Format: int32 */
            numberOfFailures?: number;
            /** Format: date-span */
            timeout?: string;
            /** Format: int32 */
            maxNumberOfRetries?: number;
            /** Format: date-time */
            createdAt?: string;
            sourceId?: string | null;
            /** Format: date-time */
            processDeadline?: string | null;
            /** Format: date-time */
            processingStartedAt?: string | null;
            /** Format: date-time */
            succeedExecutedAt?: string | null;
            workerLane?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        BucketStatus: 1 | 2 | 3 | 4 | 5 | 6;
        /**
         * Format: int32
         * @enum {integer}
         */
        ClusterMode: 1 | 2 | 3;
        /**
         * Format: int32
         * @enum {integer}
         */
        JobMasterJobStatus: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
        /**
         * Format: int32
         * @enum {integer}
         */
        JobMasterPriority: 1 | 2 | 3 | 4 | 5;
        /**
         * Format: int32
         * @enum {integer}
         */
        JobMasterTriggerSourceType: 1 | 2 | 3;
        /**
         * Format: int32
         * @enum {integer}
         */
        RecurringScheduleStatus: 1 | 2 | 3 | 4 | 5;
        /**
         * Format: int32
         * @enum {integer}
         */
        RecurringScheduleType: 2 | 3;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
