using JobMaster.Sdk.Abstractions.Serialization;

namespace JobMaster.Sdk.Abstractions.Models.GenericRecords;

/// <summary>
/// Raw message dequeued from a repository/broker.
/// - MessageId: delivery identifier generated by the repo/broker.
/// - Payload: raw JSON payload.
/// - ReferenceTime: UTC timestamp that defines ordering (ascending) for dequeue.
/// - EnqueuedAt: UTC timestamp when the message was enqueued (for diagnostics/latency).
/// - CorrelationId: optional application-level correlation identifier for tracing/idempotency.
/// </summary>
internal class JobMasterRawMessage
{
    public JobMasterRawMessage(string clusterId, string messageId, string payload, DateTime referenceTime, string correlationId)
    {
        if (string.IsNullOrWhiteSpace(messageId))
            throw new ArgumentException("messageId is required.", nameof(messageId));
        
        if (string.IsNullOrWhiteSpace(clusterId))
            throw new ArgumentException("clusterId is required.", nameof(clusterId));
        
        ClusterId = clusterId;
        MessageId = messageId;
        Payload = payload ?? throw new ArgumentNullException(nameof(payload));
        ReferenceTime = referenceTime.ToUniversalTime();
        CorrelationId = correlationId;
        EnqueuedAt = DateTime.UtcNow;
    }
    
    internal JobMasterRawMessage() { }

    public static JobMasterRawMessage RecoverFromDb(JobMasterRawMessagePersistenceRecord record)
    {
        var msg = new JobMasterRawMessage()
        {
            ClusterId = record.ClusterId,
            MessageId = record.MessageId,
            Payload = record.Payload,
            ReferenceTime = record.ReferenceTime,
            CorrelationId = record.CorrelationId,
            EnqueuedAt = record.EnqueuedAt,
        };
        
        return msg;
    }
    
    public JobMasterRawMessagePersistenceRecord ToPersistenceRecord()
    {
        return new JobMasterRawMessagePersistenceRecord
        {
            ClusterId = ClusterId,
            MessageId = MessageId,
            Payload = Payload,
            ReferenceTime = ReferenceTime,
            CorrelationId = CorrelationId,
            EnqueuedAt = EnqueuedAt,
        };
    }

    public string MessageId { get; private set; } = null!;
    public string Payload { get; private set; } = null!;
    public DateTime ReferenceTime { get; private set; }
    public string CorrelationId { get; private set; } = null!;
    public DateTime EnqueuedAt { get; private set; }
    public string ClusterId { get; set; } = null!;
    
    private const int IsoUtcLength = 28; 
    
    public static int CalcEstimateByteSize(
        string payload,
        int clusterIdLength = 256,
        int messageIdLength = 256,
        int correlationIdLength = 256,
        double safetyMultiplier = 1.1, 
        int extraBytes = 256)
    {
        var utf8 = System.Text.Encoding.UTF8;
        int size = 0;
        size += clusterIdLength;
        size += messageIdLength;
        size += utf8.GetByteCount(payload);
        size += correlationIdLength;
        
        size += IsoUtcLength; // ReferenceTime
        size += IsoUtcLength; // EnqueuedAt
        
        var padded = (int)Math.Ceiling(size * safetyMultiplier) + extraBytes;
        return padded;
    }

    public static int CalcEstimateByteSize<T>(
        T payload,
        int clusterIdLength = 256,
        int messageIdLength = 256,
        int correlationIdLength = 256,
        double safetyMultiplier = 1.1, 
        int extraBytes = 256)
    {
        string payloadJson = InternalJobMasterSerializer.Serialize<T>(payload);
        return CalcEstimateByteSize(payloadJson, clusterIdLength, messageIdLength, correlationIdLength, safetyMultiplier, extraBytes);
    }
}

internal class JobMasterRawMessagePersistenceRecord
{
    public string MessageId { get; set; } = null!;
    public string Payload { get; set; } = null!;
    public DateTime ReferenceTime { get; set; }
    public string CorrelationId { get; set; } = null!;
    public DateTime EnqueuedAt { get; set; }
    
    public string ClusterId { get; set; } = null!;
}

