/* tslint:disable */
/* eslint-disable */
/**
 * JobMaster.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * AgentConnectionsApi - axios parameter creator
 * @export
 */
export const AgentConnectionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {string} agentConnectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdAgentConnectionsAgentConnectionIdGet: async (clusterId: string, agentConnectionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdAgentConnectionsAgentConnectionIdGet', 'clusterId', clusterId)
            // verify required parameter 'agentConnectionId' is not null or undefined
            assertParamExists('jmApiClusterIdAgentConnectionsAgentConnectionIdGet', 'agentConnectionId', agentConnectionId)
            const localVarPath = `/jm-api/{clusterId}/agent-connections/{agentConnectionId}`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)))
                .replace(`{${"agentConnectionId"}}`, encodeURIComponent(String(agentConnectionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdAgentConnectionsCountGet: async (clusterId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdAgentConnectionsCountGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/agent-connections/count`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdAgentConnectionsGet: async (clusterId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdAgentConnectionsGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/agent-connections`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AgentConnectionsApi - functional programming interface
 * @export
 */
export const AgentConnectionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AgentConnectionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {string} agentConnectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdAgentConnectionsAgentConnectionIdGet(clusterId: string, agentConnectionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdAgentConnectionsAgentConnectionIdGet(clusterId, agentConnectionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentConnectionsApi.jmApiClusterIdAgentConnectionsAgentConnectionIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdAgentConnectionsCountGet(clusterId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdAgentConnectionsCountGet(clusterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentConnectionsApi.jmApiClusterIdAgentConnectionsCountGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdAgentConnectionsGet(clusterId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdAgentConnectionsGet(clusterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentConnectionsApi.jmApiClusterIdAgentConnectionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AgentConnectionsApi - factory interface
 * @export
 */
export const AgentConnectionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AgentConnectionsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {string} agentConnectionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdAgentConnectionsAgentConnectionIdGet(clusterId: string, agentConnectionId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdAgentConnectionsAgentConnectionIdGet(clusterId, agentConnectionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdAgentConnectionsCountGet(clusterId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdAgentConnectionsCountGet(clusterId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdAgentConnectionsGet(clusterId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdAgentConnectionsGet(clusterId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AgentConnectionsApi - object-oriented interface
 * @export
 * @class AgentConnectionsApi
 * @extends {BaseAPI}
 */
export class AgentConnectionsApi extends BaseAPI {
    /**
     * 
     * @param {string} clusterId 
     * @param {string} agentConnectionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentConnectionsApi
     */
    public jmApiClusterIdAgentConnectionsAgentConnectionIdGet(clusterId: string, agentConnectionId: string, options?: RawAxiosRequestConfig) {
        return AgentConnectionsApiFp(this.configuration).jmApiClusterIdAgentConnectionsAgentConnectionIdGet(clusterId, agentConnectionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentConnectionsApi
     */
    public jmApiClusterIdAgentConnectionsCountGet(clusterId: string, options?: RawAxiosRequestConfig) {
        return AgentConnectionsApiFp(this.configuration).jmApiClusterIdAgentConnectionsCountGet(clusterId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentConnectionsApi
     */
    public jmApiClusterIdAgentConnectionsGet(clusterId: string, options?: RawAxiosRequestConfig) {
        return AgentConnectionsApiFp(this.configuration).jmApiClusterIdAgentConnectionsGet(clusterId, options).then((request) => request(this.axios, this.basePath));
    }
}

