/* tslint:disable */
/* eslint-disable */
/**
 * JobMaster.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BucketStatus } from '../models';
// @ts-ignore
import type { JobMasterPriority } from '../models';
/**
 * BucketsApi - axios parameter creator
 * @export
 */
export const BucketsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {string} bucketId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdBucketsBucketIdGet: async (clusterId: string, bucketId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdBucketsBucketIdGet', 'clusterId', clusterId)
            // verify required parameter 'bucketId' is not null or undefined
            assertParamExists('jmApiClusterIdBucketsBucketIdGet', 'bucketId', bucketId)
            const localVarPath = `/jm-api/{clusterId}/buckets/{bucketId}`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)))
                .replace(`{${"bucketId"}}`, encodeURIComponent(String(bucketId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {JobMasterPriority} [priority] 
         * @param {BucketStatus} [status] 
         * @param {string} [agentWorkerId] 
         * @param {string} [workerLane] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdBucketsCountGet: async (clusterId: string, agentConnectionId?: string, priority?: JobMasterPriority, status?: BucketStatus, agentWorkerId?: string, workerLane?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdBucketsCountGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/buckets/count`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (agentConnectionId !== undefined) {
                localVarQueryParameter['AgentConnectionId'] = agentConnectionId;
            }

            if (priority !== undefined) {
                localVarQueryParameter['Priority'] = priority;
            }

            if (status !== undefined) {
                localVarQueryParameter['Status'] = status;
            }

            if (agentWorkerId !== undefined) {
                localVarQueryParameter['AgentWorkerId'] = agentWorkerId;
            }

            if (workerLane !== undefined) {
                localVarQueryParameter['WorkerLane'] = workerLane;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {JobMasterPriority} [priority] 
         * @param {BucketStatus} [status] 
         * @param {string} [agentWorkerId] 
         * @param {string} [workerLane] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdBucketsGet: async (clusterId: string, agentConnectionId?: string, priority?: JobMasterPriority, status?: BucketStatus, agentWorkerId?: string, workerLane?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdBucketsGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/buckets`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (agentConnectionId !== undefined) {
                localVarQueryParameter['AgentConnectionId'] = agentConnectionId;
            }

            if (priority !== undefined) {
                localVarQueryParameter['Priority'] = priority;
            }

            if (status !== undefined) {
                localVarQueryParameter['Status'] = status;
            }

            if (agentWorkerId !== undefined) {
                localVarQueryParameter['AgentWorkerId'] = agentWorkerId;
            }

            if (workerLane !== undefined) {
                localVarQueryParameter['WorkerLane'] = workerLane;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BucketsApi - functional programming interface
 * @export
 */
export const BucketsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BucketsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {string} bucketId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdBucketsBucketIdGet(clusterId: string, bucketId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdBucketsBucketIdGet(clusterId, bucketId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BucketsApi.jmApiClusterIdBucketsBucketIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {JobMasterPriority} [priority] 
         * @param {BucketStatus} [status] 
         * @param {string} [agentWorkerId] 
         * @param {string} [workerLane] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdBucketsCountGet(clusterId: string, agentConnectionId?: string, priority?: JobMasterPriority, status?: BucketStatus, agentWorkerId?: string, workerLane?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdBucketsCountGet(clusterId, agentConnectionId, priority, status, agentWorkerId, workerLane, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BucketsApi.jmApiClusterIdBucketsCountGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {JobMasterPriority} [priority] 
         * @param {BucketStatus} [status] 
         * @param {string} [agentWorkerId] 
         * @param {string} [workerLane] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdBucketsGet(clusterId: string, agentConnectionId?: string, priority?: JobMasterPriority, status?: BucketStatus, agentWorkerId?: string, workerLane?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdBucketsGet(clusterId, agentConnectionId, priority, status, agentWorkerId, workerLane, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BucketsApi.jmApiClusterIdBucketsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BucketsApi - factory interface
 * @export
 */
export const BucketsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BucketsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {string} bucketId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdBucketsBucketIdGet(clusterId: string, bucketId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdBucketsBucketIdGet(clusterId, bucketId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {JobMasterPriority} [priority] 
         * @param {BucketStatus} [status] 
         * @param {string} [agentWorkerId] 
         * @param {string} [workerLane] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdBucketsCountGet(clusterId: string, agentConnectionId?: string, priority?: JobMasterPriority, status?: BucketStatus, agentWorkerId?: string, workerLane?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdBucketsCountGet(clusterId, agentConnectionId, priority, status, agentWorkerId, workerLane, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {JobMasterPriority} [priority] 
         * @param {BucketStatus} [status] 
         * @param {string} [agentWorkerId] 
         * @param {string} [workerLane] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdBucketsGet(clusterId: string, agentConnectionId?: string, priority?: JobMasterPriority, status?: BucketStatus, agentWorkerId?: string, workerLane?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdBucketsGet(clusterId, agentConnectionId, priority, status, agentWorkerId, workerLane, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BucketsApi - object-oriented interface
 * @export
 * @class BucketsApi
 * @extends {BaseAPI}
 */
export class BucketsApi extends BaseAPI {
    /**
     * 
     * @param {string} clusterId 
     * @param {string} bucketId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BucketsApi
     */
    public jmApiClusterIdBucketsBucketIdGet(clusterId: string, bucketId: string, options?: RawAxiosRequestConfig) {
        return BucketsApiFp(this.configuration).jmApiClusterIdBucketsBucketIdGet(clusterId, bucketId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {string} [agentConnectionId] 
     * @param {JobMasterPriority} [priority] 
     * @param {BucketStatus} [status] 
     * @param {string} [agentWorkerId] 
     * @param {string} [workerLane] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BucketsApi
     */
    public jmApiClusterIdBucketsCountGet(clusterId: string, agentConnectionId?: string, priority?: JobMasterPriority, status?: BucketStatus, agentWorkerId?: string, workerLane?: string, options?: RawAxiosRequestConfig) {
        return BucketsApiFp(this.configuration).jmApiClusterIdBucketsCountGet(clusterId, agentConnectionId, priority, status, agentWorkerId, workerLane, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {string} [agentConnectionId] 
     * @param {JobMasterPriority} [priority] 
     * @param {BucketStatus} [status] 
     * @param {string} [agentWorkerId] 
     * @param {string} [workerLane] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BucketsApi
     */
    public jmApiClusterIdBucketsGet(clusterId: string, agentConnectionId?: string, priority?: JobMasterPriority, status?: BucketStatus, agentWorkerId?: string, workerLane?: string, options?: RawAxiosRequestConfig) {
        return BucketsApiFp(this.configuration).jmApiClusterIdBucketsGet(clusterId, agentConnectionId, priority, status, agentWorkerId, workerLane, options).then((request) => request(this.axios, this.basePath));
    }
}

