/* tslint:disable */
/* eslint-disable */
/**
 * JobMaster.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { JobMasterJobStatus } from '../models';
/**
 * JobsApi - axios parameter creator
 * @export
 */
export const JobsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {JobMasterJobStatus} [status] 
         * @param {string} [scheduledTo] 
         * @param {string} [scheduledFrom] 
         * @param {string} [processDeadlineTo] 
         * @param {string} [recurringScheduleId] 
         * @param {string} [metadataFiltersJson] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [workerLane] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdJobsCountGet: async (clusterId: string, status?: JobMasterJobStatus, scheduledTo?: string, scheduledFrom?: string, processDeadlineTo?: string, recurringScheduleId?: string, metadataFiltersJson?: string, jobDefinitionId?: string, workerLane?: string, countLimit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdJobsCountGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/jobs/count`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['Status'] = status;
            }

            if (scheduledTo !== undefined) {
                localVarQueryParameter['ScheduledTo'] = (scheduledTo as any instanceof Date) ?
                    (scheduledTo as any).toISOString() :
                    scheduledTo;
            }

            if (scheduledFrom !== undefined) {
                localVarQueryParameter['ScheduledFrom'] = (scheduledFrom as any instanceof Date) ?
                    (scheduledFrom as any).toISOString() :
                    scheduledFrom;
            }

            if (processDeadlineTo !== undefined) {
                localVarQueryParameter['ProcessDeadlineTo'] = (processDeadlineTo as any instanceof Date) ?
                    (processDeadlineTo as any).toISOString() :
                    processDeadlineTo;
            }

            if (recurringScheduleId !== undefined) {
                localVarQueryParameter['RecurringScheduleId'] = recurringScheduleId;
            }

            if (metadataFiltersJson !== undefined) {
                localVarQueryParameter['MetadataFiltersJson'] = metadataFiltersJson;
            }

            if (jobDefinitionId !== undefined) {
                localVarQueryParameter['JobDefinitionId'] = jobDefinitionId;
            }

            if (workerLane !== undefined) {
                localVarQueryParameter['WorkerLane'] = workerLane;
            }

            if (countLimit !== undefined) {
                localVarQueryParameter['CountLimit'] = countLimit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['Offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {JobMasterJobStatus} [status] 
         * @param {string} [scheduledTo] 
         * @param {string} [scheduledFrom] 
         * @param {string} [processDeadlineTo] 
         * @param {string} [recurringScheduleId] 
         * @param {string} [metadataFiltersJson] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [workerLane] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdJobsGet: async (clusterId: string, status?: JobMasterJobStatus, scheduledTo?: string, scheduledFrom?: string, processDeadlineTo?: string, recurringScheduleId?: string, metadataFiltersJson?: string, jobDefinitionId?: string, workerLane?: string, countLimit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdJobsGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/jobs`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['Status'] = status;
            }

            if (scheduledTo !== undefined) {
                localVarQueryParameter['ScheduledTo'] = (scheduledTo as any instanceof Date) ?
                    (scheduledTo as any).toISOString() :
                    scheduledTo;
            }

            if (scheduledFrom !== undefined) {
                localVarQueryParameter['ScheduledFrom'] = (scheduledFrom as any instanceof Date) ?
                    (scheduledFrom as any).toISOString() :
                    scheduledFrom;
            }

            if (processDeadlineTo !== undefined) {
                localVarQueryParameter['ProcessDeadlineTo'] = (processDeadlineTo as any instanceof Date) ?
                    (processDeadlineTo as any).toISOString() :
                    processDeadlineTo;
            }

            if (recurringScheduleId !== undefined) {
                localVarQueryParameter['RecurringScheduleId'] = recurringScheduleId;
            }

            if (metadataFiltersJson !== undefined) {
                localVarQueryParameter['MetadataFiltersJson'] = metadataFiltersJson;
            }

            if (jobDefinitionId !== undefined) {
                localVarQueryParameter['JobDefinitionId'] = jobDefinitionId;
            }

            if (workerLane !== undefined) {
                localVarQueryParameter['WorkerLane'] = workerLane;
            }

            if (countLimit !== undefined) {
                localVarQueryParameter['CountLimit'] = countLimit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['Offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdJobsIdGet: async (clusterId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdJobsIdGet', 'clusterId', clusterId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('jmApiClusterIdJobsIdGet', 'id', id)
            const localVarPath = `/jm-api/{clusterId}/jobs/{id}`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JobsApi - functional programming interface
 * @export
 */
export const JobsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JobsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {JobMasterJobStatus} [status] 
         * @param {string} [scheduledTo] 
         * @param {string} [scheduledFrom] 
         * @param {string} [processDeadlineTo] 
         * @param {string} [recurringScheduleId] 
         * @param {string} [metadataFiltersJson] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [workerLane] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdJobsCountGet(clusterId: string, status?: JobMasterJobStatus, scheduledTo?: string, scheduledFrom?: string, processDeadlineTo?: string, recurringScheduleId?: string, metadataFiltersJson?: string, jobDefinitionId?: string, workerLane?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdJobsCountGet(clusterId, status, scheduledTo, scheduledFrom, processDeadlineTo, recurringScheduleId, metadataFiltersJson, jobDefinitionId, workerLane, countLimit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.jmApiClusterIdJobsCountGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {JobMasterJobStatus} [status] 
         * @param {string} [scheduledTo] 
         * @param {string} [scheduledFrom] 
         * @param {string} [processDeadlineTo] 
         * @param {string} [recurringScheduleId] 
         * @param {string} [metadataFiltersJson] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [workerLane] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdJobsGet(clusterId: string, status?: JobMasterJobStatus, scheduledTo?: string, scheduledFrom?: string, processDeadlineTo?: string, recurringScheduleId?: string, metadataFiltersJson?: string, jobDefinitionId?: string, workerLane?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdJobsGet(clusterId, status, scheduledTo, scheduledFrom, processDeadlineTo, recurringScheduleId, metadataFiltersJson, jobDefinitionId, workerLane, countLimit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.jmApiClusterIdJobsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdJobsIdGet(clusterId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdJobsIdGet(clusterId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobsApi.jmApiClusterIdJobsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JobsApi - factory interface
 * @export
 */
export const JobsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JobsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {JobMasterJobStatus} [status] 
         * @param {string} [scheduledTo] 
         * @param {string} [scheduledFrom] 
         * @param {string} [processDeadlineTo] 
         * @param {string} [recurringScheduleId] 
         * @param {string} [metadataFiltersJson] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [workerLane] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdJobsCountGet(clusterId: string, status?: JobMasterJobStatus, scheduledTo?: string, scheduledFrom?: string, processDeadlineTo?: string, recurringScheduleId?: string, metadataFiltersJson?: string, jobDefinitionId?: string, workerLane?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdJobsCountGet(clusterId, status, scheduledTo, scheduledFrom, processDeadlineTo, recurringScheduleId, metadataFiltersJson, jobDefinitionId, workerLane, countLimit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {JobMasterJobStatus} [status] 
         * @param {string} [scheduledTo] 
         * @param {string} [scheduledFrom] 
         * @param {string} [processDeadlineTo] 
         * @param {string} [recurringScheduleId] 
         * @param {string} [metadataFiltersJson] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [workerLane] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdJobsGet(clusterId: string, status?: JobMasterJobStatus, scheduledTo?: string, scheduledFrom?: string, processDeadlineTo?: string, recurringScheduleId?: string, metadataFiltersJson?: string, jobDefinitionId?: string, workerLane?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdJobsGet(clusterId, status, scheduledTo, scheduledFrom, processDeadlineTo, recurringScheduleId, metadataFiltersJson, jobDefinitionId, workerLane, countLimit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdJobsIdGet(clusterId: string, id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdJobsIdGet(clusterId, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JobsApi - object-oriented interface
 * @export
 * @class JobsApi
 * @extends {BaseAPI}
 */
export class JobsApi extends BaseAPI {
    /**
     * 
     * @param {string} clusterId 
     * @param {JobMasterJobStatus} [status] 
     * @param {string} [scheduledTo] 
     * @param {string} [scheduledFrom] 
     * @param {string} [processDeadlineTo] 
     * @param {string} [recurringScheduleId] 
     * @param {string} [metadataFiltersJson] 
     * @param {string} [jobDefinitionId] 
     * @param {string} [workerLane] 
     * @param {number} [countLimit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public jmApiClusterIdJobsCountGet(clusterId: string, status?: JobMasterJobStatus, scheduledTo?: string, scheduledFrom?: string, processDeadlineTo?: string, recurringScheduleId?: string, metadataFiltersJson?: string, jobDefinitionId?: string, workerLane?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).jmApiClusterIdJobsCountGet(clusterId, status, scheduledTo, scheduledFrom, processDeadlineTo, recurringScheduleId, metadataFiltersJson, jobDefinitionId, workerLane, countLimit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {JobMasterJobStatus} [status] 
     * @param {string} [scheduledTo] 
     * @param {string} [scheduledFrom] 
     * @param {string} [processDeadlineTo] 
     * @param {string} [recurringScheduleId] 
     * @param {string} [metadataFiltersJson] 
     * @param {string} [jobDefinitionId] 
     * @param {string} [workerLane] 
     * @param {number} [countLimit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public jmApiClusterIdJobsGet(clusterId: string, status?: JobMasterJobStatus, scheduledTo?: string, scheduledFrom?: string, processDeadlineTo?: string, recurringScheduleId?: string, metadataFiltersJson?: string, jobDefinitionId?: string, workerLane?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).jmApiClusterIdJobsGet(clusterId, status, scheduledTo, scheduledFrom, processDeadlineTo, recurringScheduleId, metadataFiltersJson, jobDefinitionId, workerLane, countLimit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApi
     */
    public jmApiClusterIdJobsIdGet(clusterId: string, id: string, options?: RawAxiosRequestConfig) {
        return JobsApiFp(this.configuration).jmApiClusterIdJobsIdGet(clusterId, id, options).then((request) => request(this.axios, this.basePath));
    }
}

