/* tslint:disable */
/* eslint-disable */
/**
 * JobMaster.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiJobMasterLogLevel } from '../models';
// @ts-ignore
import type { ApiJobMasterLogSubjectType } from '../models';
/**
 * LogsApi - axios parameter creator
 * @export
 */
export const LogsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {ApiJobMasterLogLevel} [level] 
         * @param {ApiJobMasterLogSubjectType} [subjectType] 
         * @param {string} [subjectId] 
         * @param {string} [fromTimestamp] 
         * @param {string} [toTimestamp] 
         * @param {string} [keyword] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdLogsCountGet: async (clusterId: string, level?: ApiJobMasterLogLevel, subjectType?: ApiJobMasterLogSubjectType, subjectId?: string, fromTimestamp?: string, toTimestamp?: string, keyword?: string, countLimit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdLogsCountGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/logs/count`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (level !== undefined) {
                localVarQueryParameter['Level'] = level;
            }

            if (subjectType !== undefined) {
                localVarQueryParameter['SubjectType'] = subjectType;
            }

            if (subjectId !== undefined) {
                localVarQueryParameter['SubjectId'] = subjectId;
            }

            if (fromTimestamp !== undefined) {
                localVarQueryParameter['FromTimestamp'] = (fromTimestamp as any instanceof Date) ?
                    (fromTimestamp as any).toISOString() :
                    fromTimestamp;
            }

            if (toTimestamp !== undefined) {
                localVarQueryParameter['ToTimestamp'] = (toTimestamp as any instanceof Date) ?
                    (toTimestamp as any).toISOString() :
                    toTimestamp;
            }

            if (keyword !== undefined) {
                localVarQueryParameter['Keyword'] = keyword;
            }

            if (countLimit !== undefined) {
                localVarQueryParameter['CountLimit'] = countLimit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['Offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {ApiJobMasterLogLevel} [level] 
         * @param {ApiJobMasterLogSubjectType} [subjectType] 
         * @param {string} [subjectId] 
         * @param {string} [fromTimestamp] 
         * @param {string} [toTimestamp] 
         * @param {string} [keyword] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdLogsGet: async (clusterId: string, level?: ApiJobMasterLogLevel, subjectType?: ApiJobMasterLogSubjectType, subjectId?: string, fromTimestamp?: string, toTimestamp?: string, keyword?: string, countLimit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdLogsGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/logs`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (level !== undefined) {
                localVarQueryParameter['Level'] = level;
            }

            if (subjectType !== undefined) {
                localVarQueryParameter['SubjectType'] = subjectType;
            }

            if (subjectId !== undefined) {
                localVarQueryParameter['SubjectId'] = subjectId;
            }

            if (fromTimestamp !== undefined) {
                localVarQueryParameter['FromTimestamp'] = (fromTimestamp as any instanceof Date) ?
                    (fromTimestamp as any).toISOString() :
                    fromTimestamp;
            }

            if (toTimestamp !== undefined) {
                localVarQueryParameter['ToTimestamp'] = (toTimestamp as any instanceof Date) ?
                    (toTimestamp as any).toISOString() :
                    toTimestamp;
            }

            if (keyword !== undefined) {
                localVarQueryParameter['Keyword'] = keyword;
            }

            if (countLimit !== undefined) {
                localVarQueryParameter['CountLimit'] = countLimit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['Offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdLogsIdGet: async (clusterId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdLogsIdGet', 'clusterId', clusterId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('jmApiClusterIdLogsIdGet', 'id', id)
            const localVarPath = `/jm-api/{clusterId}/logs/{id}`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LogsApi - functional programming interface
 * @export
 */
export const LogsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LogsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {ApiJobMasterLogLevel} [level] 
         * @param {ApiJobMasterLogSubjectType} [subjectType] 
         * @param {string} [subjectId] 
         * @param {string} [fromTimestamp] 
         * @param {string} [toTimestamp] 
         * @param {string} [keyword] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdLogsCountGet(clusterId: string, level?: ApiJobMasterLogLevel, subjectType?: ApiJobMasterLogSubjectType, subjectId?: string, fromTimestamp?: string, toTimestamp?: string, keyword?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdLogsCountGet(clusterId, level, subjectType, subjectId, fromTimestamp, toTimestamp, keyword, countLimit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LogsApi.jmApiClusterIdLogsCountGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {ApiJobMasterLogLevel} [level] 
         * @param {ApiJobMasterLogSubjectType} [subjectType] 
         * @param {string} [subjectId] 
         * @param {string} [fromTimestamp] 
         * @param {string} [toTimestamp] 
         * @param {string} [keyword] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdLogsGet(clusterId: string, level?: ApiJobMasterLogLevel, subjectType?: ApiJobMasterLogSubjectType, subjectId?: string, fromTimestamp?: string, toTimestamp?: string, keyword?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdLogsGet(clusterId, level, subjectType, subjectId, fromTimestamp, toTimestamp, keyword, countLimit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LogsApi.jmApiClusterIdLogsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdLogsIdGet(clusterId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdLogsIdGet(clusterId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LogsApi.jmApiClusterIdLogsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LogsApi - factory interface
 * @export
 */
export const LogsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LogsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {ApiJobMasterLogLevel} [level] 
         * @param {ApiJobMasterLogSubjectType} [subjectType] 
         * @param {string} [subjectId] 
         * @param {string} [fromTimestamp] 
         * @param {string} [toTimestamp] 
         * @param {string} [keyword] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdLogsCountGet(clusterId: string, level?: ApiJobMasterLogLevel, subjectType?: ApiJobMasterLogSubjectType, subjectId?: string, fromTimestamp?: string, toTimestamp?: string, keyword?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdLogsCountGet(clusterId, level, subjectType, subjectId, fromTimestamp, toTimestamp, keyword, countLimit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {ApiJobMasterLogLevel} [level] 
         * @param {ApiJobMasterLogSubjectType} [subjectType] 
         * @param {string} [subjectId] 
         * @param {string} [fromTimestamp] 
         * @param {string} [toTimestamp] 
         * @param {string} [keyword] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdLogsGet(clusterId: string, level?: ApiJobMasterLogLevel, subjectType?: ApiJobMasterLogSubjectType, subjectId?: string, fromTimestamp?: string, toTimestamp?: string, keyword?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdLogsGet(clusterId, level, subjectType, subjectId, fromTimestamp, toTimestamp, keyword, countLimit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdLogsIdGet(clusterId: string, id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdLogsIdGet(clusterId, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LogsApi - object-oriented interface
 * @export
 * @class LogsApi
 * @extends {BaseAPI}
 */
export class LogsApi extends BaseAPI {
    /**
     * 
     * @param {string} clusterId 
     * @param {ApiJobMasterLogLevel} [level] 
     * @param {ApiJobMasterLogSubjectType} [subjectType] 
     * @param {string} [subjectId] 
     * @param {string} [fromTimestamp] 
     * @param {string} [toTimestamp] 
     * @param {string} [keyword] 
     * @param {number} [countLimit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LogsApi
     */
    public jmApiClusterIdLogsCountGet(clusterId: string, level?: ApiJobMasterLogLevel, subjectType?: ApiJobMasterLogSubjectType, subjectId?: string, fromTimestamp?: string, toTimestamp?: string, keyword?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return LogsApiFp(this.configuration).jmApiClusterIdLogsCountGet(clusterId, level, subjectType, subjectId, fromTimestamp, toTimestamp, keyword, countLimit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {ApiJobMasterLogLevel} [level] 
     * @param {ApiJobMasterLogSubjectType} [subjectType] 
     * @param {string} [subjectId] 
     * @param {string} [fromTimestamp] 
     * @param {string} [toTimestamp] 
     * @param {string} [keyword] 
     * @param {number} [countLimit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LogsApi
     */
    public jmApiClusterIdLogsGet(clusterId: string, level?: ApiJobMasterLogLevel, subjectType?: ApiJobMasterLogSubjectType, subjectId?: string, fromTimestamp?: string, toTimestamp?: string, keyword?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return LogsApiFp(this.configuration).jmApiClusterIdLogsGet(clusterId, level, subjectType, subjectId, fromTimestamp, toTimestamp, keyword, countLimit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LogsApi
     */
    public jmApiClusterIdLogsIdGet(clusterId: string, id: string, options?: RawAxiosRequestConfig) {
        return LogsApiFp(this.configuration).jmApiClusterIdLogsIdGet(clusterId, id, options).then((request) => request(this.axios, this.basePath));
    }
}

