/* tslint:disable */
/* eslint-disable */
/**
 * JobMaster.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RecurringScheduleStatus } from '../models';
// @ts-ignore
import type { RecurringScheduleType } from '../models';
/**
 * RecurringSchedulesApi - axios parameter creator
 * @export
 */
export const RecurringSchedulesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {RecurringScheduleStatus} [status] 
         * @param {string} [startAfterTo] 
         * @param {string} [startAfterFrom] 
         * @param {string} [endBeforeTo] 
         * @param {string} [endBeforeFrom] 
         * @param {string} [coverageUntil] 
         * @param {boolean} [isJobCancellationPending] 
         * @param {boolean} [canceledOrInactive] 
         * @param {RecurringScheduleType} [recurringScheduleType] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [profileId] 
         * @param {string} [workerLane] 
         * @param {string} [metadataFiltersJson] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdRecurringSchedulesCountGet: async (clusterId: string, status?: RecurringScheduleStatus, startAfterTo?: string, startAfterFrom?: string, endBeforeTo?: string, endBeforeFrom?: string, coverageUntil?: string, isJobCancellationPending?: boolean, canceledOrInactive?: boolean, recurringScheduleType?: RecurringScheduleType, jobDefinitionId?: string, profileId?: string, workerLane?: string, metadataFiltersJson?: string, countLimit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdRecurringSchedulesCountGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/recurring-schedules/count`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['Status'] = status;
            }

            if (startAfterTo !== undefined) {
                localVarQueryParameter['StartAfterTo'] = (startAfterTo as any instanceof Date) ?
                    (startAfterTo as any).toISOString() :
                    startAfterTo;
            }

            if (startAfterFrom !== undefined) {
                localVarQueryParameter['StartAfterFrom'] = (startAfterFrom as any instanceof Date) ?
                    (startAfterFrom as any).toISOString() :
                    startAfterFrom;
            }

            if (endBeforeTo !== undefined) {
                localVarQueryParameter['EndBeforeTo'] = (endBeforeTo as any instanceof Date) ?
                    (endBeforeTo as any).toISOString() :
                    endBeforeTo;
            }

            if (endBeforeFrom !== undefined) {
                localVarQueryParameter['EndBeforeFrom'] = (endBeforeFrom as any instanceof Date) ?
                    (endBeforeFrom as any).toISOString() :
                    endBeforeFrom;
            }

            if (coverageUntil !== undefined) {
                localVarQueryParameter['CoverageUntil'] = (coverageUntil as any instanceof Date) ?
                    (coverageUntil as any).toISOString() :
                    coverageUntil;
            }

            if (isJobCancellationPending !== undefined) {
                localVarQueryParameter['IsJobCancellationPending'] = isJobCancellationPending;
            }

            if (canceledOrInactive !== undefined) {
                localVarQueryParameter['CanceledOrInactive'] = canceledOrInactive;
            }

            if (recurringScheduleType !== undefined) {
                localVarQueryParameter['RecurringScheduleType'] = recurringScheduleType;
            }

            if (jobDefinitionId !== undefined) {
                localVarQueryParameter['JobDefinitionId'] = jobDefinitionId;
            }

            if (profileId !== undefined) {
                localVarQueryParameter['ProfileId'] = profileId;
            }

            if (workerLane !== undefined) {
                localVarQueryParameter['WorkerLane'] = workerLane;
            }

            if (metadataFiltersJson !== undefined) {
                localVarQueryParameter['MetadataFiltersJson'] = metadataFiltersJson;
            }

            if (countLimit !== undefined) {
                localVarQueryParameter['CountLimit'] = countLimit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['Offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {RecurringScheduleStatus} [status] 
         * @param {string} [startAfterTo] 
         * @param {string} [startAfterFrom] 
         * @param {string} [endBeforeTo] 
         * @param {string} [endBeforeFrom] 
         * @param {string} [coverageUntil] 
         * @param {boolean} [isJobCancellationPending] 
         * @param {boolean} [canceledOrInactive] 
         * @param {RecurringScheduleType} [recurringScheduleType] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [profileId] 
         * @param {string} [workerLane] 
         * @param {string} [metadataFiltersJson] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdRecurringSchedulesGet: async (clusterId: string, status?: RecurringScheduleStatus, startAfterTo?: string, startAfterFrom?: string, endBeforeTo?: string, endBeforeFrom?: string, coverageUntil?: string, isJobCancellationPending?: boolean, canceledOrInactive?: boolean, recurringScheduleType?: RecurringScheduleType, jobDefinitionId?: string, profileId?: string, workerLane?: string, metadataFiltersJson?: string, countLimit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdRecurringSchedulesGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/recurring-schedules`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['Status'] = status;
            }

            if (startAfterTo !== undefined) {
                localVarQueryParameter['StartAfterTo'] = (startAfterTo as any instanceof Date) ?
                    (startAfterTo as any).toISOString() :
                    startAfterTo;
            }

            if (startAfterFrom !== undefined) {
                localVarQueryParameter['StartAfterFrom'] = (startAfterFrom as any instanceof Date) ?
                    (startAfterFrom as any).toISOString() :
                    startAfterFrom;
            }

            if (endBeforeTo !== undefined) {
                localVarQueryParameter['EndBeforeTo'] = (endBeforeTo as any instanceof Date) ?
                    (endBeforeTo as any).toISOString() :
                    endBeforeTo;
            }

            if (endBeforeFrom !== undefined) {
                localVarQueryParameter['EndBeforeFrom'] = (endBeforeFrom as any instanceof Date) ?
                    (endBeforeFrom as any).toISOString() :
                    endBeforeFrom;
            }

            if (coverageUntil !== undefined) {
                localVarQueryParameter['CoverageUntil'] = (coverageUntil as any instanceof Date) ?
                    (coverageUntil as any).toISOString() :
                    coverageUntil;
            }

            if (isJobCancellationPending !== undefined) {
                localVarQueryParameter['IsJobCancellationPending'] = isJobCancellationPending;
            }

            if (canceledOrInactive !== undefined) {
                localVarQueryParameter['CanceledOrInactive'] = canceledOrInactive;
            }

            if (recurringScheduleType !== undefined) {
                localVarQueryParameter['RecurringScheduleType'] = recurringScheduleType;
            }

            if (jobDefinitionId !== undefined) {
                localVarQueryParameter['JobDefinitionId'] = jobDefinitionId;
            }

            if (profileId !== undefined) {
                localVarQueryParameter['ProfileId'] = profileId;
            }

            if (workerLane !== undefined) {
                localVarQueryParameter['WorkerLane'] = workerLane;
            }

            if (metadataFiltersJson !== undefined) {
                localVarQueryParameter['MetadataFiltersJson'] = metadataFiltersJson;
            }

            if (countLimit !== undefined) {
                localVarQueryParameter['CountLimit'] = countLimit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['Offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdRecurringSchedulesIdGet: async (clusterId: string, id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdRecurringSchedulesIdGet', 'clusterId', clusterId)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('jmApiClusterIdRecurringSchedulesIdGet', 'id', id)
            const localVarPath = `/jm-api/{clusterId}/recurring-schedules/{id}`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecurringSchedulesApi - functional programming interface
 * @export
 */
export const RecurringSchedulesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecurringSchedulesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {RecurringScheduleStatus} [status] 
         * @param {string} [startAfterTo] 
         * @param {string} [startAfterFrom] 
         * @param {string} [endBeforeTo] 
         * @param {string} [endBeforeFrom] 
         * @param {string} [coverageUntil] 
         * @param {boolean} [isJobCancellationPending] 
         * @param {boolean} [canceledOrInactive] 
         * @param {RecurringScheduleType} [recurringScheduleType] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [profileId] 
         * @param {string} [workerLane] 
         * @param {string} [metadataFiltersJson] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdRecurringSchedulesCountGet(clusterId: string, status?: RecurringScheduleStatus, startAfterTo?: string, startAfterFrom?: string, endBeforeTo?: string, endBeforeFrom?: string, coverageUntil?: string, isJobCancellationPending?: boolean, canceledOrInactive?: boolean, recurringScheduleType?: RecurringScheduleType, jobDefinitionId?: string, profileId?: string, workerLane?: string, metadataFiltersJson?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdRecurringSchedulesCountGet(clusterId, status, startAfterTo, startAfterFrom, endBeforeTo, endBeforeFrom, coverageUntil, isJobCancellationPending, canceledOrInactive, recurringScheduleType, jobDefinitionId, profileId, workerLane, metadataFiltersJson, countLimit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecurringSchedulesApi.jmApiClusterIdRecurringSchedulesCountGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {RecurringScheduleStatus} [status] 
         * @param {string} [startAfterTo] 
         * @param {string} [startAfterFrom] 
         * @param {string} [endBeforeTo] 
         * @param {string} [endBeforeFrom] 
         * @param {string} [coverageUntil] 
         * @param {boolean} [isJobCancellationPending] 
         * @param {boolean} [canceledOrInactive] 
         * @param {RecurringScheduleType} [recurringScheduleType] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [profileId] 
         * @param {string} [workerLane] 
         * @param {string} [metadataFiltersJson] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdRecurringSchedulesGet(clusterId: string, status?: RecurringScheduleStatus, startAfterTo?: string, startAfterFrom?: string, endBeforeTo?: string, endBeforeFrom?: string, coverageUntil?: string, isJobCancellationPending?: boolean, canceledOrInactive?: boolean, recurringScheduleType?: RecurringScheduleType, jobDefinitionId?: string, profileId?: string, workerLane?: string, metadataFiltersJson?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdRecurringSchedulesGet(clusterId, status, startAfterTo, startAfterFrom, endBeforeTo, endBeforeFrom, coverageUntil, isJobCancellationPending, canceledOrInactive, recurringScheduleType, jobDefinitionId, profileId, workerLane, metadataFiltersJson, countLimit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecurringSchedulesApi.jmApiClusterIdRecurringSchedulesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdRecurringSchedulesIdGet(clusterId: string, id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdRecurringSchedulesIdGet(clusterId, id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecurringSchedulesApi.jmApiClusterIdRecurringSchedulesIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RecurringSchedulesApi - factory interface
 * @export
 */
export const RecurringSchedulesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecurringSchedulesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {RecurringScheduleStatus} [status] 
         * @param {string} [startAfterTo] 
         * @param {string} [startAfterFrom] 
         * @param {string} [endBeforeTo] 
         * @param {string} [endBeforeFrom] 
         * @param {string} [coverageUntil] 
         * @param {boolean} [isJobCancellationPending] 
         * @param {boolean} [canceledOrInactive] 
         * @param {RecurringScheduleType} [recurringScheduleType] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [profileId] 
         * @param {string} [workerLane] 
         * @param {string} [metadataFiltersJson] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdRecurringSchedulesCountGet(clusterId: string, status?: RecurringScheduleStatus, startAfterTo?: string, startAfterFrom?: string, endBeforeTo?: string, endBeforeFrom?: string, coverageUntil?: string, isJobCancellationPending?: boolean, canceledOrInactive?: boolean, recurringScheduleType?: RecurringScheduleType, jobDefinitionId?: string, profileId?: string, workerLane?: string, metadataFiltersJson?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdRecurringSchedulesCountGet(clusterId, status, startAfterTo, startAfterFrom, endBeforeTo, endBeforeFrom, coverageUntil, isJobCancellationPending, canceledOrInactive, recurringScheduleType, jobDefinitionId, profileId, workerLane, metadataFiltersJson, countLimit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {RecurringScheduleStatus} [status] 
         * @param {string} [startAfterTo] 
         * @param {string} [startAfterFrom] 
         * @param {string} [endBeforeTo] 
         * @param {string} [endBeforeFrom] 
         * @param {string} [coverageUntil] 
         * @param {boolean} [isJobCancellationPending] 
         * @param {boolean} [canceledOrInactive] 
         * @param {RecurringScheduleType} [recurringScheduleType] 
         * @param {string} [jobDefinitionId] 
         * @param {string} [profileId] 
         * @param {string} [workerLane] 
         * @param {string} [metadataFiltersJson] 
         * @param {number} [countLimit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdRecurringSchedulesGet(clusterId: string, status?: RecurringScheduleStatus, startAfterTo?: string, startAfterFrom?: string, endBeforeTo?: string, endBeforeFrom?: string, coverageUntil?: string, isJobCancellationPending?: boolean, canceledOrInactive?: boolean, recurringScheduleType?: RecurringScheduleType, jobDefinitionId?: string, profileId?: string, workerLane?: string, metadataFiltersJson?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdRecurringSchedulesGet(clusterId, status, startAfterTo, startAfterFrom, endBeforeTo, endBeforeFrom, coverageUntil, isJobCancellationPending, canceledOrInactive, recurringScheduleType, jobDefinitionId, profileId, workerLane, metadataFiltersJson, countLimit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdRecurringSchedulesIdGet(clusterId: string, id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdRecurringSchedulesIdGet(clusterId, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecurringSchedulesApi - object-oriented interface
 * @export
 * @class RecurringSchedulesApi
 * @extends {BaseAPI}
 */
export class RecurringSchedulesApi extends BaseAPI {
    /**
     * 
     * @param {string} clusterId 
     * @param {RecurringScheduleStatus} [status] 
     * @param {string} [startAfterTo] 
     * @param {string} [startAfterFrom] 
     * @param {string} [endBeforeTo] 
     * @param {string} [endBeforeFrom] 
     * @param {string} [coverageUntil] 
     * @param {boolean} [isJobCancellationPending] 
     * @param {boolean} [canceledOrInactive] 
     * @param {RecurringScheduleType} [recurringScheduleType] 
     * @param {string} [jobDefinitionId] 
     * @param {string} [profileId] 
     * @param {string} [workerLane] 
     * @param {string} [metadataFiltersJson] 
     * @param {number} [countLimit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecurringSchedulesApi
     */
    public jmApiClusterIdRecurringSchedulesCountGet(clusterId: string, status?: RecurringScheduleStatus, startAfterTo?: string, startAfterFrom?: string, endBeforeTo?: string, endBeforeFrom?: string, coverageUntil?: string, isJobCancellationPending?: boolean, canceledOrInactive?: boolean, recurringScheduleType?: RecurringScheduleType, jobDefinitionId?: string, profileId?: string, workerLane?: string, metadataFiltersJson?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return RecurringSchedulesApiFp(this.configuration).jmApiClusterIdRecurringSchedulesCountGet(clusterId, status, startAfterTo, startAfterFrom, endBeforeTo, endBeforeFrom, coverageUntil, isJobCancellationPending, canceledOrInactive, recurringScheduleType, jobDefinitionId, profileId, workerLane, metadataFiltersJson, countLimit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {RecurringScheduleStatus} [status] 
     * @param {string} [startAfterTo] 
     * @param {string} [startAfterFrom] 
     * @param {string} [endBeforeTo] 
     * @param {string} [endBeforeFrom] 
     * @param {string} [coverageUntil] 
     * @param {boolean} [isJobCancellationPending] 
     * @param {boolean} [canceledOrInactive] 
     * @param {RecurringScheduleType} [recurringScheduleType] 
     * @param {string} [jobDefinitionId] 
     * @param {string} [profileId] 
     * @param {string} [workerLane] 
     * @param {string} [metadataFiltersJson] 
     * @param {number} [countLimit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecurringSchedulesApi
     */
    public jmApiClusterIdRecurringSchedulesGet(clusterId: string, status?: RecurringScheduleStatus, startAfterTo?: string, startAfterFrom?: string, endBeforeTo?: string, endBeforeFrom?: string, coverageUntil?: string, isJobCancellationPending?: boolean, canceledOrInactive?: boolean, recurringScheduleType?: RecurringScheduleType, jobDefinitionId?: string, profileId?: string, workerLane?: string, metadataFiltersJson?: string, countLimit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return RecurringSchedulesApiFp(this.configuration).jmApiClusterIdRecurringSchedulesGet(clusterId, status, startAfterTo, startAfterFrom, endBeforeTo, endBeforeFrom, coverageUntil, isJobCancellationPending, canceledOrInactive, recurringScheduleType, jobDefinitionId, profileId, workerLane, metadataFiltersJson, countLimit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecurringSchedulesApi
     */
    public jmApiClusterIdRecurringSchedulesIdGet(clusterId: string, id: string, options?: RawAxiosRequestConfig) {
        return RecurringSchedulesApiFp(this.configuration).jmApiClusterIdRecurringSchedulesIdGet(clusterId, id, options).then((request) => request(this.axios, this.basePath));
    }
}

