/* tslint:disable */
/* eslint-disable */
/**
 * JobMaster.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AgentWorkerMode } from '../models';
// @ts-ignore
import type { AgentWorkerStatus } from '../models';
/**
 * WorkersApi - axios parameter creator
 * @export
 */
export const WorkersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {string} [workerLane] 
         * @param {AgentWorkerStatus} [status] 
         * @param {AgentWorkerMode} [mode] 
         * @param {boolean} [isAlive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdWorkersCountGet: async (clusterId: string, agentConnectionId?: string, workerLane?: string, status?: AgentWorkerStatus, mode?: AgentWorkerMode, isAlive?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdWorkersCountGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/workers/count`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (agentConnectionId !== undefined) {
                localVarQueryParameter['AgentConnectionId'] = agentConnectionId;
            }

            if (workerLane !== undefined) {
                localVarQueryParameter['WorkerLane'] = workerLane;
            }

            if (status !== undefined) {
                localVarQueryParameter['Status'] = status;
            }

            if (mode !== undefined) {
                localVarQueryParameter['Mode'] = mode;
            }

            if (isAlive !== undefined) {
                localVarQueryParameter['IsAlive'] = isAlive;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {string} [workerLane] 
         * @param {AgentWorkerStatus} [status] 
         * @param {AgentWorkerMode} [mode] 
         * @param {boolean} [isAlive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdWorkersGet: async (clusterId: string, agentConnectionId?: string, workerLane?: string, status?: AgentWorkerStatus, mode?: AgentWorkerMode, isAlive?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdWorkersGet', 'clusterId', clusterId)
            const localVarPath = `/jm-api/{clusterId}/workers`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (agentConnectionId !== undefined) {
                localVarQueryParameter['AgentConnectionId'] = agentConnectionId;
            }

            if (workerLane !== undefined) {
                localVarQueryParameter['WorkerLane'] = workerLane;
            }

            if (status !== undefined) {
                localVarQueryParameter['Status'] = status;
            }

            if (mode !== undefined) {
                localVarQueryParameter['Mode'] = mode;
            }

            if (isAlive !== undefined) {
                localVarQueryParameter['IsAlive'] = isAlive;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} workerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdWorkersWorkerIdGet: async (clusterId: string, workerId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clusterId' is not null or undefined
            assertParamExists('jmApiClusterIdWorkersWorkerIdGet', 'clusterId', clusterId)
            // verify required parameter 'workerId' is not null or undefined
            assertParamExists('jmApiClusterIdWorkersWorkerIdGet', 'workerId', workerId)
            const localVarPath = `/jm-api/{clusterId}/workers/{workerId}`
                .replace(`{${"clusterId"}}`, encodeURIComponent(String(clusterId)))
                .replace(`{${"workerId"}}`, encodeURIComponent(String(workerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WorkersApi - functional programming interface
 * @export
 */
export const WorkersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WorkersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {string} [workerLane] 
         * @param {AgentWorkerStatus} [status] 
         * @param {AgentWorkerMode} [mode] 
         * @param {boolean} [isAlive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdWorkersCountGet(clusterId: string, agentConnectionId?: string, workerLane?: string, status?: AgentWorkerStatus, mode?: AgentWorkerMode, isAlive?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdWorkersCountGet(clusterId, agentConnectionId, workerLane, status, mode, isAlive, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkersApi.jmApiClusterIdWorkersCountGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {string} [workerLane] 
         * @param {AgentWorkerStatus} [status] 
         * @param {AgentWorkerMode} [mode] 
         * @param {boolean} [isAlive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdWorkersGet(clusterId: string, agentConnectionId?: string, workerLane?: string, status?: AgentWorkerStatus, mode?: AgentWorkerMode, isAlive?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdWorkersGet(clusterId, agentConnectionId, workerLane, status, mode, isAlive, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkersApi.jmApiClusterIdWorkersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} workerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jmApiClusterIdWorkersWorkerIdGet(clusterId: string, workerId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jmApiClusterIdWorkersWorkerIdGet(clusterId, workerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WorkersApi.jmApiClusterIdWorkersWorkerIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WorkersApi - factory interface
 * @export
 */
export const WorkersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WorkersApiFp(configuration)
    return {
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {string} [workerLane] 
         * @param {AgentWorkerStatus} [status] 
         * @param {AgentWorkerMode} [mode] 
         * @param {boolean} [isAlive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdWorkersCountGet(clusterId: string, agentConnectionId?: string, workerLane?: string, status?: AgentWorkerStatus, mode?: AgentWorkerMode, isAlive?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdWorkersCountGet(clusterId, agentConnectionId, workerLane, status, mode, isAlive, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} [agentConnectionId] 
         * @param {string} [workerLane] 
         * @param {AgentWorkerStatus} [status] 
         * @param {AgentWorkerMode} [mode] 
         * @param {boolean} [isAlive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdWorkersGet(clusterId: string, agentConnectionId?: string, workerLane?: string, status?: AgentWorkerStatus, mode?: AgentWorkerMode, isAlive?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdWorkersGet(clusterId, agentConnectionId, workerLane, status, mode, isAlive, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} clusterId 
         * @param {string} workerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jmApiClusterIdWorkersWorkerIdGet(clusterId: string, workerId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jmApiClusterIdWorkersWorkerIdGet(clusterId, workerId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WorkersApi - object-oriented interface
 * @export
 * @class WorkersApi
 * @extends {BaseAPI}
 */
export class WorkersApi extends BaseAPI {
    /**
     * 
     * @param {string} clusterId 
     * @param {string} [agentConnectionId] 
     * @param {string} [workerLane] 
     * @param {AgentWorkerStatus} [status] 
     * @param {AgentWorkerMode} [mode] 
     * @param {boolean} [isAlive] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkersApi
     */
    public jmApiClusterIdWorkersCountGet(clusterId: string, agentConnectionId?: string, workerLane?: string, status?: AgentWorkerStatus, mode?: AgentWorkerMode, isAlive?: boolean, options?: RawAxiosRequestConfig) {
        return WorkersApiFp(this.configuration).jmApiClusterIdWorkersCountGet(clusterId, agentConnectionId, workerLane, status, mode, isAlive, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {string} [agentConnectionId] 
     * @param {string} [workerLane] 
     * @param {AgentWorkerStatus} [status] 
     * @param {AgentWorkerMode} [mode] 
     * @param {boolean} [isAlive] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkersApi
     */
    public jmApiClusterIdWorkersGet(clusterId: string, agentConnectionId?: string, workerLane?: string, status?: AgentWorkerStatus, mode?: AgentWorkerMode, isAlive?: boolean, options?: RawAxiosRequestConfig) {
        return WorkersApiFp(this.configuration).jmApiClusterIdWorkersGet(clusterId, agentConnectionId, workerLane, status, mode, isAlive, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} clusterId 
     * @param {string} workerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkersApi
     */
    public jmApiClusterIdWorkersWorkerIdGet(clusterId: string, workerId: string, options?: RawAxiosRequestConfig) {
        return WorkersApiFp(this.configuration).jmApiClusterIdWorkersWorkerIdGet(clusterId, workerId, options).then((request) => request(this.axios, this.basePath));
    }
}

